{application,client,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{publisher,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[subscriber]},
              {licenses,["Apache-2.0"]},
              {links,[]}]}.
